let initialValues = {
  firstName: "",
  lastName: "",
  email: "",
  tomography: "",
  doctor: "",
  birthday: "",
  gender: null,
  period: "",
  research: null,
  researchType: null,
  contrast: null,
  purposeOfPrevention: null,
  complains: "",
  hasOperation: null,
  operation: "",
  haschronicDisease: null,
  chronicDisease: "",
  hasOncologicalDisease: null,
  oncologicalDisease: "",
  hasChemotherapy: null,
  chemotherapy: "",
  otherResearches: [],
};

export default initialValues;
